version: 0.0
os: linux
files:
  - source: /
    destination: /home/heartlab-api
hooks:
  BeforeInstall:
    - location: before_install.sh
  AfterInstall:
    - location: after_install.sh
    runas: ec2-user
  ApplicationStart:
    - location: application_start.sh
    runas: ec2-user
