version: 0.0
os: linux
files:
  - source: /
    destination: /home/heartlab-api
hooks:
  ApplicationStop:
    - location: application_stop.sh
  BeforeInstall:
    - location: before_install.sh
  AfterInstall:
    - location: after_install.sh
  ApplicationStart:
    - location: application_start.sh
